// GraphQL Module Exports for Rent It Forward Shared Package
// Export GraphQL-specific types with namespace to avoid conflicts
export type {
  User as GraphQLUser,
  Listing as GraphQLListing,
  Booking as GraphQLBooking,
  Review as GraphQLReview,
  Payment as GraphQLPayment,
  Message as GraphQLMessage,
  Conversation as GraphQLConversation,
  Category as GraphQLCategory,
  ListingPhoto as GraphQLListingPhoto,
  ListingAvailability as GraphQLListingAvailability,
  Favorite as GraphQLFavorite,
  Notification as GraphQLNotification,
  Incentive as GraphQLIncentive,
  BookingStatus as GraphQLBookingStatus,
  CreateListingInput as GraphQLCreateListingInput,
  UpdateListingInput as GraphQLUpdateListingInput,
  CreateBookingInput as GraphQLCreateBookingInput,
  CreateReviewInput as GraphQLCreateReviewInput,
  SendMessageInput as GraphQLSendMessageInput,
  UpdateProfileInput as GraphQLUpdateProfileInput,
  ListingFilter as GraphQLListingFilter,
  ListingSort as GraphQLListingSort,
  BookingFilter as GraphQLBookingFilter,
  BookingSort as GraphQLBookingSort,
  SearchInput as GraphQLSearchInput,
  SearchResult as GraphQLSearchResult,
  Connection,
  ListingConnection,
  BookingConnection,
  ReviewConnection,
  MessageConnection,
  NotificationConnection,
  PageInfo,
  UserDashboard,
  AdminDashboard,
  GraphQLError,
  MutationResponse,
  CreateListingResponse,
  CreateBookingResponse,
  CreateReviewResponse,
  SendMessageResponse,
  UpdateProfileResponse
} from './types';

export { typeDefs } from './schema';
export * from './client'; 